version: "3"

services: 
  web:
    container_name: node-krowdy
    restart: always
    build: .
    ports:
      - "8085:3000"
    links:
      - mongo
    
  mongo:
    container_name: mongo-krowdy
    image: mongo
    ports:
      - "8077:27017"

